Repository wecode-bootcamp-korea/40-backend-westagram-1, pull requests merged in 2022-11, with the labels that each got.

#1 [40기-정재헌]Assignment1:Express API-초기 환경 세팅
  JeongJaeHeon/.env.sample
  JeongJaeHeon/.gitignore
  JeongJaeHeon/app.js
  JeongJaeHeon/package-lock.json
  JeongJaeHeon/package.json
Labels: 멘토 리뷰 요청

#11 [40기 - 윤형준] Assignment 1: Express API - 초기 환경 세팅
  hyungjoonYoon/.env.sample
  hyungjoonYoon/.gitignore
  hyungjoonYoon/app.js
  hyungjoonYoon/db/migrations/20221122152112_users.sql
  hyungjoonYoon/db/migrations/20221122152116_posts.sql
  hyungjoonYoon/db/migrations/20221122152121_likes.sql
  hyungjoonYoon/db/migrations/20221122152125_comments.sql
  hyungjoonYoon/package-lock.json
  hyungjoonYoon/package.json
Labels: 멘토 리뷰 요청

#10 [40기 정재헌] Assignment 2: Express API - 유저 회원가입 하기
  JeongJaeHeon/.gitignore
  JeongJaeHeon/Screenshot from 2022-11-26 16-09-44.png
  JeongJaeHeon/[40기 정재헌]Assignment2:Westagram Backend Project-유저 회원 가입 구현-DB캡처본
  JeongJaeHeon/app.js
  JeongJaeHeon/db/migrations/20221126023026_create_users_tables.sql
  JeongJaeHeon/db/migrations/20221126023034_create_posts_tables.sql
  JeongJaeHeon/db/migrations/20221126065152_create_likes_tables.sql
  JeongJaeHeon/db/migrations/20221128012938_create_users_tables.sql
  JeongJaeHeon/db/migrations/20221128013054_create_likes_tables.sql
  JeongJaeHeon/db/migrations/20221128050048_create_posts_tables.sql
Labels: 완료

#15 [40기-윤형준] Assignment 2 : Express API - 유저 회원가입 하기
  hyungjoonYoon/app.js
  hyungjoonYoon/dbStatus.png
Labels: 멘토 리뷰 요청

#17 [40기 정재헌]Assignment2 error fix
  JeongJaeHeon/[40기 정재헌]Assignment2:Westagram Backend Project-유저 회원 가입 구현-DB캡처본
Labels: 멘토 리뷰 요청

#8 [40기-박진주] Assignment 1 : Express API - 초기 환경 세팅
  ParkJInjoo/.gitignore
  ParkJInjoo/app.js
  ParkJInjoo/db/migrations/20221124114623_create_users_table.sql
  ParkJInjoo/db/migrations/20221124114638_create_posts_table.sql
  ParkJInjoo/package-lock.json
  ParkJInjoo/package.json
Labels: 멘토 리뷰 요청, 수정 요청

#9 [40기 -김영석] Assignment 2: Express API - 유저 회원가입 하기
  kimyeongseok/.env.sample
  kimyeongseok/.gitignore
  kimyeongseok/app.js
  kimyeongseok/db/migrations/20221123131901_create_posts_table.sql
  kimyeongseok/db/migrations/20221123131911_create_likes_table.sql
  kimyeongseok/db/migrations/20221123131920_create_comments_table.sql
  kimyeongseok/db/migrations/20221124055617_create_users_table.sql
  kimyeongseok/db/migrations/20221124071412_update_users.sql
  kimyeongseok/db/migrations/20221128062636_modify_users_table.sql
  kimyeongseok/db/migrations/20221128063550_modify_likes_table.sql
  kimyeongseok/db/migrations/20221128083535_modify_users_uniquekey.sql
  kimyeongseok/package-lock.json
  kimyeongseok/package.json
Labels: 멘토 리뷰 요청

#6 [40기-박진주] Assignment 2 : Express API - 유저 회원가입 하기
  ParkJInjoo/.env.sample
  ParkJInjoo/app.js
Labels: 멘토 리뷰 요청, 수정 요청

#16 [40기 김영석] Assignment 3-8 CRUD 구현하기
  kimyeongseok/app.js
  kimyeongseok/db/migrations/20221128071850_modify_users_table.sql
  kimyeongseok/db/migrations/20221128072029_modify_likes_table.sql
Labels: 멘토 리뷰 요청
